config:
  project_repos:
    sqaas-web:
      repo: 'https://github.com/EOSC-synergy/sqaaas-web.git'
      branch: jpl-branch
  credentials:
      - id: token_sqaaas_web
        variable: GITHUB_TOKEN

sqa_criteria:
  qc_doc:
    repos:
      sqaas-web:
        container: testing-jpl-sqaaas
        commands:
          - ls -a /testing-jpl-sqaaas
          - sh /testing-jpl-sqaaas/script.sh
