config:
  project_repos:
    sqaas-web:
      repo: 'https://github.com/EOSC-synergy/sqaaas-web.git'

sqa_criteria:
  qc_doc:
    repos:
      sqaas-web:
        container: sqaaas-testing
        commands:
          - sh /sqaaas-testing/script.sh
          
